version: '2'

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    env_file: .env
    ports:
      - "127.0.0.1:5671:5671"
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    logging:
      driver: journald
      options:
        tag: rabbitmq

  postgres:
    image: postgres:9.4
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./dockerfiles/pgdata:/var/lib/postgresql/data/pgdata

  web:
    build: ./app
    env_file: .env
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8000:80"
